{"num_games": 100, "student_agent_wins": [0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1], "random_agent_wins": [1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0], "student_agent_win_count": 27, "random_agent_win_count": 73, "student_agent_win_percentage": 0.27, "random_agent_win_percentage": 0.73, "student_agent_time_taken": 0.0036579132080078124, "random_agent_time_taken": 0.0030742311477661133, "run_info": [{"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.002675771713256836, "random_agent_time": 0.0018038749694824219, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.0038747787475585938, "random_agent_time": 0.0020155906677246094, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.0003330707550048828, "random_agent_time": 0.0008237361907958984, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.0014777183532714844, "random_agent_time": 0.0020880699157714844, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.003927469253540039, "random_agent_time": 0.0050506591796875, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.0022232532501220703, "random_agent_time": 0.002064943313598633, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.00037479400634765625, "random_agent_time": 0.001489877700805664, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.002210855484008789, "random_agent_time": 0.001967906951904297, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004552125930786133, "random_agent_time": 0.002774477005004883, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.0003421306610107422, "random_agent_time": 0.0008711814880371094, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0037262439727783203, "random_agent_time": 0.002077341079711914, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.002646923065185547, "random_agent_time": 0.0027794837951660156, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.004336118698120117, "random_agent_time": 0.006545543670654297, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003201007843017578, "random_agent_time": 0.0024237632751464844, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0032422542572021484, "random_agent_time": 0.0026352405548095703, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.003247976303100586, "random_agent_time": 0.0023310184478759766, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.0034677982330322266, "random_agent_time": 0.0032563209533691406, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0028715133666992188, "random_agent_time": 0.002207040786743164, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0041162967681884766, "random_agent_time": 0.0025374889373779297, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.005887746810913086, "random_agent_time": 0.005743741989135742, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0035729408264160156, "random_agent_time": 0.0038003921508789062, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002645730972290039, "random_agent_time": 0.002166271209716797, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.008049726486206055, "random_agent_time": 0.0074956417083740234, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.00493621826171875, "random_agent_time": 0.003656148910522461, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.003976345062255859, "random_agent_time": 0.004347801208496094, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.0044782161712646484, "random_agent_time": 0.002808809280395508, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.010047197341918945, "random_agent_time": 0.006920337677001953, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004021644592285156, "random_agent_time": 0.0025484561920166016, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.0021469593048095703, "random_agent_time": 0.0021486282348632812, "board_size": 6, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004019737243652344, "random_agent_time": 0.0019261837005615234, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.001954793930053711, "random_agent_time": 0.0023016929626464844, "board_size": 6, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0037260055541992188, "random_agent_time": 0.0021584033966064453, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.002580404281616211, "random_agent_time": 0.002744913101196289, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004667758941650391, "random_agent_time": 0.0020797252655029297, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.009143352508544922, "random_agent_time": 0.007002353668212891, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.0016880035400390625, "random_agent_time": 0.0034983158111572266, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0052411556243896484, "random_agent_time": 0.001947641372680664, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.0015861988067626953, "random_agent_time": 0.0020334720611572266, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0030565261840820312, "random_agent_time": 0.0034165382385253906, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004102945327758789, "random_agent_time": 0.0036537647247314453, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.004933834075927734, "random_agent_time": 0.004937648773193359, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.0015716552734375, "random_agent_time": 0.0014042854309082031, "board_size": 6, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004113435745239258, "random_agent_time": 0.0019860267639160156, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0027000904083251953, "random_agent_time": 0.0027992725372314453, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0025191307067871094, "random_agent_time": 0.0022444725036621094, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.0023412704467773438, "random_agent_time": 0.0018603801727294922, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.0029141902923583984, "random_agent_time": 0.002123117446899414, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.0070645809173583984, "random_agent_time": 0.008294820785522461, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0042266845703125, "random_agent_time": 0.0016393661499023438, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003016233444213867, "random_agent_time": 0.002081632614135742, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.0033538341522216797, "random_agent_time": 0.0027866363525390625, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0027534961700439453, "random_agent_time": 0.0023336410522460938, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.0003528594970703125, "random_agent_time": 0.0020284652709960938, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.00039076805114746094, "random_agent_time": 0.0018286705017089844, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004509687423706055, "random_agent_time": 0.0022792816162109375, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0024175643920898438, "random_agent_time": 0.0021321773529052734, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.00403904914855957, "random_agent_time": 0.0025014877319335938, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.005416154861450195, "random_agent_time": 0.0022373199462890625, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004387855529785156, "random_agent_time": 0.0020444393157958984, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0031523704528808594, "random_agent_time": 0.0024607181549072266, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.00516963005065918, "random_agent_time": 0.00624847412109375, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.002924203872680664, "random_agent_time": 0.0027773380279541016, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.005153179168701172, "random_agent_time": 0.0063381195068359375, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004337787628173828, "random_agent_time": 0.002716541290283203, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0032958984375, "random_agent_time": 0.002702951431274414, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0027801990509033203, "random_agent_time": 0.002717733383178711, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0050144195556640625, "random_agent_time": 0.002436399459838867, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003817319869995117, "random_agent_time": 0.0025534629821777344, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.0025026798248291016, "random_agent_time": 0.003118753433227539, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.009353876113891602, "random_agent_time": 0.008725643157958984, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.00251007080078125, "random_agent_time": 0.002811908721923828, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002879619598388672, "random_agent_time": 0.002939462661743164, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004220247268676758, "random_agent_time": 0.002097606658935547, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004749298095703125, "random_agent_time": 0.0020074844360351562, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004677295684814453, "random_agent_time": 0.003341197967529297, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.0019044876098632812, "random_agent_time": 0.0014269351959228516, "board_size": 6, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0025048255920410156, "random_agent_time": 0.0028722286224365234, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.0009279251098632812, "random_agent_time": 0.0014529228210449219, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003739595413208008, "random_agent_time": 0.0029668807983398438, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.004868030548095703, "random_agent_time": 0.006720542907714844, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004793882369995117, "random_agent_time": 0.0020062923431396484, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0033860206604003906, "random_agent_time": 0.0026481151580810547, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002925395965576172, "random_agent_time": 0.0028886795043945312, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.008235692977905273, "random_agent_time": 0.010080099105834961, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0025703907012939453, "random_agent_time": 0.0028471946716308594, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003180265426635742, "random_agent_time": 0.002683401107788086, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.0034637451171875, "random_agent_time": 0.0021123886108398438, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0030815601348876953, "random_agent_time": 0.002447366714477539, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002707958221435547, "random_agent_time": 0.002180337905883789, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.0033330917358398438, "random_agent_time": 0.0018763542175292969, "board_size": 6, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.0026013851165771484, "random_agent_time": 0.0020601749420166016, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0024819374084472656, "random_agent_time": 0.0021300315856933594, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.00038504600524902344, "random_agent_time": 0.0011782646179199219, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0040111541748046875, "random_agent_time": 0.0018661022186279297, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004265546798706055, "random_agent_time": 0.003130197525024414, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.005821704864501953, "random_agent_time": 0.0028367042541503906, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004014730453491211, "random_agent_time": 0.002803802490234375, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0027866363525390625, "random_agent_time": 0.002917051315307617, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.007277011871337891, "random_agent_time": 0.007002115249633789, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.006585121154785156, "random_agent_time": 0.006609201431274414, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}]}