{"num_games": 100, "student_agent_wins": [0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], "random_agent_wins": [1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1], "student_agent_win_count": 29, "random_agent_win_count": 71, "student_agent_win_percentage": 0.29, "random_agent_win_percentage": 0.71, "student_agent_time_taken": 0.003950929641723633, "random_agent_time_taken": 0.0034750032424926756, "run_info": [{"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.005063772201538086, "random_agent_time": 0.006937742233276367, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.002347707748413086, "random_agent_time": 0.0025408267974853516, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.005273580551147461, "random_agent_time": 0.0025076866149902344, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004496335983276367, "random_agent_time": 0.0033066272735595703, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.005194187164306641, "random_agent_time": 0.005180835723876953, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0022516250610351562, "random_agent_time": 0.0018117427825927734, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0036079883575439453, "random_agent_time": 0.0020148754119873047, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004752159118652344, "random_agent_time": 0.0018377304077148438, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0032758712768554688, "random_agent_time": 0.0042798519134521484, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.0003921985626220703, "random_agent_time": 0.0011496543884277344, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.006659507751464844, "random_agent_time": 0.005862712860107422, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004472255706787109, "random_agent_time": 0.0021877288818359375, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0021941661834716797, "random_agent_time": 0.003211498260498047, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.003023862838745117, "random_agent_time": 0.0019648075103759766, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0030553340911865234, "random_agent_time": 0.003019094467163086, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004434823989868164, "random_agent_time": 0.0022618770599365234, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.004772663116455078, "random_agent_time": 0.004912376403808594, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.009074687957763672, "random_agent_time": 0.00844430923461914, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.00250244140625, "random_agent_time": 0.00327301025390625, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.0032677650451660156, "random_agent_time": 0.0029609203338623047, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004956960678100586, "random_agent_time": 0.0021147727966308594, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.0018954277038574219, "random_agent_time": 0.0008482933044433594, "board_size": 6, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.009218215942382812, "random_agent_time": 0.007329702377319336, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.004462718963623047, "random_agent_time": 0.006058216094970703, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002359628677368164, "random_agent_time": 0.002227783203125, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.00482177734375, "random_agent_time": 0.004335641860961914, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.005083560943603516, "random_agent_time": 0.0027649402618408203, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.002727985382080078, "random_agent_time": 0.002804279327392578, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0038192272186279297, "random_agent_time": 0.0024406909942626953, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.004316806793212891, "random_agent_time": 0.0030868053436279297, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.0028264522552490234, "random_agent_time": 0.001990795135498047, "board_size": 6, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002529621124267578, "random_agent_time": 0.0032036304473876953, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.003524303436279297, "random_agent_time": 0.002573728561401367, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.0029180049896240234, "random_agent_time": 0.002828836441040039, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004644155502319336, "random_agent_time": 0.0025458335876464844, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.0006356239318847656, "random_agent_time": 0.0009865760803222656, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.002594470977783203, "random_agent_time": 0.0024628639221191406, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.00031375885009765625, "random_agent_time": 0.0009183883666992188, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.00028634071350097656, "random_agent_time": 0.0011601448059082031, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004854917526245117, "random_agent_time": 0.002941131591796875, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.0019168853759765625, "random_agent_time": 0.0030121803283691406, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004775524139404297, "random_agent_time": 0.002352476119995117, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.004195213317871094, "random_agent_time": 0.005840301513671875, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0069849491119384766, "random_agent_time": 0.003408670425415039, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.010252237319946289, "random_agent_time": 0.008676290512084961, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.0017821788787841797, "random_agent_time": 0.002349376678466797, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.004404544830322266, "random_agent_time": 0.005524158477783203, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0041043758392333984, "random_agent_time": 0.0034151077270507812, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003740072250366211, "random_agent_time": 0.001821756362915039, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.0017490386962890625, "random_agent_time": 0.001708984375, "board_size": 6, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.0034623146057128906, "random_agent_time": 0.0030820369720458984, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.00470423698425293, "random_agent_time": 0.002705097198486328, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.0025937557220458984, "random_agent_time": 0.0022416114807128906, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.005841732025146484, "random_agent_time": 0.005479097366333008, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0023818016052246094, "random_agent_time": 0.002281665802001953, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.005275249481201172, "random_agent_time": 0.002433300018310547, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.00035691261291503906, "random_agent_time": 0.0008075237274169922, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002664804458618164, "random_agent_time": 0.0025377273559570312, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.00865316390991211, "random_agent_time": 0.00824284553527832, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002570629119873047, "random_agent_time": 0.0023097991943359375, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.004903078079223633, "random_agent_time": 0.006410837173461914, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.00479888916015625, "random_agent_time": 0.0031752586364746094, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.008953571319580078, "random_agent_time": 0.008214235305786133, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.0016543865203857422, "random_agent_time": 0.0016252994537353516, "board_size": 6, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.00472569465637207, "random_agent_time": 0.0019371509552001953, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.004220485687255859, "random_agent_time": 0.0020859241485595703, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003895998001098633, "random_agent_time": 0.002218961715698242, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.001588582992553711, "random_agent_time": 0.002048492431640625, "board_size": 6, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002491474151611328, "random_agent_time": 0.002106189727783203, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.003040313720703125, "random_agent_time": 0.006211519241333008, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004112958908081055, "random_agent_time": 0.0038175582885742188, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003992795944213867, "random_agent_time": 0.0036056041717529297, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0035147666931152344, "random_agent_time": 0.0032510757446289062, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.006750822067260742, "random_agent_time": 0.0059087276458740234, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.008433818817138672, "random_agent_time": 0.007617950439453125, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0024487972259521484, "random_agent_time": 0.002614259719848633, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002612590789794922, "random_agent_time": 0.004150390625, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.004026889801025391, "random_agent_time": 0.0020291805267333984, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002671957015991211, "random_agent_time": 0.002119302749633789, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.002147674560546875, "random_agent_time": 0.0023157596588134766, "board_size": 6, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.005162715911865234, "random_agent_time": 0.002445697784423828, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.0051996707916259766, "random_agent_time": 0.005803346633911133, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0029256343841552734, "random_agent_time": 0.002203226089477539, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.0025262832641601562, "random_agent_time": 0.002242565155029297, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.005040168762207031, "random_agent_time": 0.002254962921142578, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0034487247467041016, "random_agent_time": 0.002531766891479492, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002411365509033203, "random_agent_time": 0.0030019283294677734, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.007963418960571289, "random_agent_time": 0.00835561752319336, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.007080554962158203, "random_agent_time": 0.0071523189544677734, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.004023551940917969, "random_agent_time": 0.003230571746826172, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002471923828125, "random_agent_time": 0.003644227981567383, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003718852996826172, "random_agent_time": 0.0061681270599365234, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0028672218322753906, "random_agent_time": 0.0024766921997070312, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.0018763542175292969, "random_agent_time": 0.0008900165557861328, "board_size": 6, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0044286251068115234, "random_agent_time": 0.0024116039276123047, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.0017862319946289062, "random_agent_time": 0.0015790462493896484, "board_size": 6, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.0046901702880859375, "random_agent_time": 0.006402254104614258, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.004406929016113281, "random_agent_time": 0.005230903625488281, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.007105350494384766, "random_agent_time": 0.006166934967041016, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.0036611557006835938, "random_agent_time": 0.00432586669921875, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-momo-kat/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}]}